/** Comprehensive list of country dialing codes with flag emojis — 195+ countries */
export interface CountryCodeEntry {
  code: string;   // e.g. "+971"
  iso: string;    // e.g. "AE"
  flag: string;   // e.g. "🇦🇪"
  label: string;  // e.g. "🇦🇪 +971"
  name: string;   // e.g. "United Arab Emirates"
}

const ALL_COUNTRY_CODES: CountryCodeEntry[] = [
  { code: "+93", iso: "AF", flag: "🇦🇫", label: "🇦🇫 +93", name: "Afghanistan" },
  { code: "+355", iso: "AL", flag: "🇦🇱", label: "🇦🇱 +355", name: "Albania" },
  { code: "+213", iso: "DZ", flag: "🇩🇿", label: "🇩🇿 +213", name: "Algeria" },
  { code: "+376", iso: "AD", flag: "🇦🇩", label: "🇦🇩 +376", name: "Andorra" },
  { code: "+244", iso: "AO", flag: "🇦🇴", label: "🇦🇴 +244", name: "Angola" },
  { code: "+1", iso: "AG", flag: "🇦🇬", label: "🇦🇬 +1", name: "Antigua & Barbuda" },
  { code: "+54", iso: "AR", flag: "🇦🇷", label: "🇦🇷 +54", name: "Argentina" },
  { code: "+374", iso: "AM", flag: "🇦🇲", label: "🇦🇲 +374", name: "Armenia" },
  { code: "+61", iso: "AU", flag: "🇦🇺", label: "🇦🇺 +61", name: "Australia" },
  { code: "+43", iso: "AT", flag: "🇦🇹", label: "🇦🇹 +43", name: "Austria" },
  { code: "+994", iso: "AZ", flag: "🇦🇿", label: "🇦🇿 +994", name: "Azerbaijan" },
  { code: "+1", iso: "BS", flag: "🇧🇸", label: "🇧🇸 +1", name: "Bahamas" },
  { code: "+973", iso: "BH", flag: "🇧🇭", label: "🇧🇭 +973", name: "Bahrain" },
  { code: "+880", iso: "BD", flag: "🇧🇩", label: "🇧🇩 +880", name: "Bangladesh" },
  { code: "+1", iso: "BB", flag: "🇧🇧", label: "🇧🇧 +1", name: "Barbados" },
  { code: "+375", iso: "BY", flag: "🇧🇾", label: "🇧🇾 +375", name: "Belarus" },
  { code: "+32", iso: "BE", flag: "🇧🇪", label: "🇧🇪 +32", name: "Belgium" },
  { code: "+501", iso: "BZ", flag: "🇧🇿", label: "🇧🇿 +501", name: "Belize" },
  { code: "+229", iso: "BJ", flag: "🇧🇯", label: "🇧🇯 +229", name: "Benin" },
  { code: "+975", iso: "BT", flag: "🇧🇹", label: "🇧🇹 +975", name: "Bhutan" },
  { code: "+591", iso: "BO", flag: "🇧🇴", label: "🇧🇴 +591", name: "Bolivia" },
  { code: "+387", iso: "BA", flag: "🇧🇦", label: "🇧🇦 +387", name: "Bosnia" },
  { code: "+267", iso: "BW", flag: "🇧🇼", label: "🇧🇼 +267", name: "Botswana" },
  { code: "+55", iso: "BR", flag: "🇧🇷", label: "🇧🇷 +55", name: "Brazil" },
  { code: "+673", iso: "BN", flag: "🇧🇳", label: "🇧🇳 +673", name: "Brunei" },
  { code: "+359", iso: "BG", flag: "🇧🇬", label: "🇧🇬 +359", name: "Bulgaria" },
  { code: "+226", iso: "BF", flag: "🇧🇫", label: "🇧🇫 +226", name: "Burkina Faso" },
  { code: "+257", iso: "BI", flag: "🇧🇮", label: "🇧🇮 +257", name: "Burundi" },
  { code: "+855", iso: "KH", flag: "🇰🇭", label: "🇰🇭 +855", name: "Cambodia" },
  { code: "+237", iso: "CM", flag: "🇨🇲", label: "🇨🇲 +237", name: "Cameroon" },
  { code: "+1", iso: "CA", flag: "🇨🇦", label: "🇨🇦 +1", name: "Canada" },
  { code: "+238", iso: "CV", flag: "🇨🇻", label: "🇨🇻 +238", name: "Cape Verde" },
  { code: "+236", iso: "CF", flag: "🇨🇫", label: "🇨🇫 +236", name: "Central African Republic" },
  { code: "+235", iso: "TD", flag: "🇹🇩", label: "🇹🇩 +235", name: "Chad" },
  { code: "+56", iso: "CL", flag: "🇨🇱", label: "🇨🇱 +56", name: "Chile" },
  { code: "+86", iso: "CN", flag: "🇨🇳", label: "🇨🇳 +86", name: "China" },
  { code: "+57", iso: "CO", flag: "🇨🇴", label: "🇨🇴 +57", name: "Colombia" },
  { code: "+269", iso: "KM", flag: "🇰🇲", label: "🇰🇲 +269", name: "Comoros" },
  { code: "+242", iso: "CG", flag: "🇨🇬", label: "🇨🇬 +242", name: "Congo" },
  { code: "+243", iso: "CD", flag: "🇨🇩", label: "🇨🇩 +243", name: "Congo (DRC)" },
  { code: "+506", iso: "CR", flag: "🇨🇷", label: "🇨🇷 +506", name: "Costa Rica" },
  { code: "+225", iso: "CI", flag: "🇨🇮", label: "🇨🇮 +225", name: "Côte d'Ivoire" },
  { code: "+385", iso: "HR", flag: "🇭🇷", label: "🇭🇷 +385", name: "Croatia" },
  { code: "+53", iso: "CU", flag: "🇨🇺", label: "🇨🇺 +53", name: "Cuba" },
  { code: "+357", iso: "CY", flag: "🇨🇾", label: "🇨🇾 +357", name: "Cyprus" },
  { code: "+420", iso: "CZ", flag: "🇨🇿", label: "🇨🇿 +420", name: "Czech Republic" },
  { code: "+45", iso: "DK", flag: "🇩🇰", label: "🇩🇰 +45", name: "Denmark" },
  { code: "+253", iso: "DJ", flag: "🇩🇯", label: "🇩🇯 +253", name: "Djibouti" },
  { code: "+1", iso: "DM", flag: "🇩🇲", label: "🇩🇲 +1", name: "Dominica" },
  { code: "+1", iso: "DO", flag: "🇩🇴", label: "🇩🇴 +1", name: "Dominican Republic" },
  { code: "+593", iso: "EC", flag: "🇪🇨", label: "🇪🇨 +593", name: "Ecuador" },
  { code: "+20", iso: "EG", flag: "🇪🇬", label: "🇪🇬 +20", name: "Egypt" },
  { code: "+503", iso: "SV", flag: "🇸🇻", label: "🇸🇻 +503", name: "El Salvador" },
  { code: "+240", iso: "GQ", flag: "🇬🇶", label: "🇬🇶 +240", name: "Equatorial Guinea" },
  { code: "+291", iso: "ER", flag: "🇪🇷", label: "🇪🇷 +291", name: "Eritrea" },
  { code: "+372", iso: "EE", flag: "🇪🇪", label: "🇪🇪 +372", name: "Estonia" },
  { code: "+268", iso: "SZ", flag: "🇸🇿", label: "🇸🇿 +268", name: "Eswatini" },
  { code: "+251", iso: "ET", flag: "🇪🇹", label: "🇪🇹 +251", name: "Ethiopia" },
  { code: "+679", iso: "FJ", flag: "🇫🇯", label: "🇫🇯 +679", name: "Fiji" },
  { code: "+358", iso: "FI", flag: "🇫🇮", label: "🇫🇮 +358", name: "Finland" },
  { code: "+33", iso: "FR", flag: "🇫🇷", label: "🇫🇷 +33", name: "France" },
  { code: "+241", iso: "GA", flag: "🇬🇦", label: "🇬🇦 +241", name: "Gabon" },
  { code: "+220", iso: "GM", flag: "🇬🇲", label: "🇬🇲 +220", name: "Gambia" },
  { code: "+995", iso: "GE", flag: "🇬🇪", label: "🇬🇪 +995", name: "Georgia" },
  { code: "+49", iso: "DE", flag: "🇩🇪", label: "🇩🇪 +49", name: "Germany" },
  { code: "+233", iso: "GH", flag: "🇬🇭", label: "🇬🇭 +233", name: "Ghana" },
  { code: "+30", iso: "GR", flag: "🇬🇷", label: "🇬🇷 +30", name: "Greece" },
  { code: "+1", iso: "GD", flag: "🇬🇩", label: "🇬🇩 +1", name: "Grenada" },
  { code: "+502", iso: "GT", flag: "🇬🇹", label: "🇬🇹 +502", name: "Guatemala" },
  { code: "+224", iso: "GN", flag: "🇬🇳", label: "🇬🇳 +224", name: "Guinea" },
  { code: "+245", iso: "GW", flag: "🇬🇼", label: "🇬🇼 +245", name: "Guinea-Bissau" },
  { code: "+592", iso: "GY", flag: "🇬🇾", label: "🇬🇾 +592", name: "Guyana" },
  { code: "+509", iso: "HT", flag: "🇭🇹", label: "🇭🇹 +509", name: "Haiti" },
  { code: "+504", iso: "HN", flag: "🇭🇳", label: "🇭🇳 +504", name: "Honduras" },
  { code: "+852", iso: "HK", flag: "🇭🇰", label: "🇭🇰 +852", name: "Hong Kong" },
  { code: "+36", iso: "HU", flag: "🇭🇺", label: "🇭🇺 +36", name: "Hungary" },
  { code: "+354", iso: "IS", flag: "🇮🇸", label: "🇮🇸 +354", name: "Iceland" },
  { code: "+91", iso: "IN", flag: "🇮🇳", label: "🇮🇳 +91", name: "India" },
  { code: "+62", iso: "ID", flag: "🇮🇩", label: "🇮🇩 +62", name: "Indonesia" },
  { code: "+98", iso: "IR", flag: "🇮🇷", label: "🇮🇷 +98", name: "Iran" },
  { code: "+964", iso: "IQ", flag: "🇮🇶", label: "🇮🇶 +964", name: "Iraq" },
  { code: "+353", iso: "IE", flag: "🇮🇪", label: "🇮🇪 +353", name: "Ireland" },
  { code: "+972", iso: "IL", flag: "🇮🇱", label: "🇮🇱 +972", name: "Israel" },
  { code: "+39", iso: "IT", flag: "🇮🇹", label: "🇮🇹 +39", name: "Italy" },
  { code: "+1", iso: "JM", flag: "🇯🇲", label: "🇯🇲 +1", name: "Jamaica" },
  { code: "+81", iso: "JP", flag: "🇯🇵", label: "🇯🇵 +81", name: "Japan" },
  { code: "+962", iso: "JO", flag: "🇯🇴", label: "🇯🇴 +962", name: "Jordan" },
  { code: "+7", iso: "KZ", flag: "🇰🇿", label: "🇰🇿 +7", name: "Kazakhstan" },
  { code: "+254", iso: "KE", flag: "🇰🇪", label: "🇰🇪 +254", name: "Kenya" },
  { code: "+686", iso: "KI", flag: "🇰🇮", label: "🇰🇮 +686", name: "Kiribati" },
  { code: "+965", iso: "KW", flag: "🇰🇼", label: "🇰🇼 +965", name: "Kuwait" },
  { code: "+996", iso: "KG", flag: "🇰🇬", label: "🇰🇬 +996", name: "Kyrgyzstan" },
  { code: "+856", iso: "LA", flag: "🇱🇦", label: "🇱🇦 +856", name: "Laos" },
  { code: "+371", iso: "LV", flag: "🇱🇻", label: "🇱🇻 +371", name: "Latvia" },
  { code: "+961", iso: "LB", flag: "🇱🇧", label: "🇱🇧 +961", name: "Lebanon" },
  { code: "+266", iso: "LS", flag: "🇱🇸", label: "🇱🇸 +266", name: "Lesotho" },
  { code: "+231", iso: "LR", flag: "🇱🇷", label: "🇱🇷 +231", name: "Liberia" },
  { code: "+218", iso: "LY", flag: "🇱🇾", label: "🇱🇾 +218", name: "Libya" },
  { code: "+423", iso: "LI", flag: "🇱🇮", label: "🇱🇮 +423", name: "Liechtenstein" },
  { code: "+370", iso: "LT", flag: "🇱🇹", label: "🇱🇹 +370", name: "Lithuania" },
  { code: "+352", iso: "LU", flag: "🇱🇺", label: "🇱🇺 +352", name: "Luxembourg" },
  { code: "+853", iso: "MO", flag: "🇲🇴", label: "🇲🇴 +853", name: "Macau" },
  { code: "+261", iso: "MG", flag: "🇲🇬", label: "🇲🇬 +261", name: "Madagascar" },
  { code: "+265", iso: "MW", flag: "🇲🇼", label: "🇲🇼 +265", name: "Malawi" },
  { code: "+60", iso: "MY", flag: "🇲🇾", label: "🇲🇾 +60", name: "Malaysia" },
  { code: "+960", iso: "MV", flag: "🇲🇻", label: "🇲🇻 +960", name: "Maldives" },
  { code: "+223", iso: "ML", flag: "🇲🇱", label: "🇲🇱 +223", name: "Mali" },
  { code: "+356", iso: "MT", flag: "🇲🇹", label: "🇲🇹 +356", name: "Malta" },
  { code: "+692", iso: "MH", flag: "🇲🇭", label: "🇲🇭 +692", name: "Marshall Islands" },
  { code: "+222", iso: "MR", flag: "🇲🇷", label: "🇲🇷 +222", name: "Mauritania" },
  { code: "+230", iso: "MU", flag: "🇲🇺", label: "🇲🇺 +230", name: "Mauritius" },
  { code: "+52", iso: "MX", flag: "🇲🇽", label: "🇲🇽 +52", name: "Mexico" },
  { code: "+691", iso: "FM", flag: "🇫🇲", label: "🇫🇲 +691", name: "Micronesia" },
  { code: "+373", iso: "MD", flag: "🇲🇩", label: "🇲🇩 +373", name: "Moldova" },
  { code: "+377", iso: "MC", flag: "🇲🇨", label: "🇲🇨 +377", name: "Monaco" },
  { code: "+976", iso: "MN", flag: "🇲🇳", label: "🇲🇳 +976", name: "Mongolia" },
  { code: "+382", iso: "ME", flag: "🇲🇪", label: "🇲🇪 +382", name: "Montenegro" },
  { code: "+212", iso: "MA", flag: "🇲🇦", label: "🇲🇦 +212", name: "Morocco" },
  { code: "+258", iso: "MZ", flag: "🇲🇿", label: "🇲🇿 +258", name: "Mozambique" },
  { code: "+95", iso: "MM", flag: "🇲🇲", label: "🇲🇲 +95", name: "Myanmar" },
  { code: "+264", iso: "NA", flag: "🇳🇦", label: "🇳🇦 +264", name: "Namibia" },
  { code: "+674", iso: "NR", flag: "🇳🇷", label: "🇳🇷 +674", name: "Nauru" },
  { code: "+977", iso: "NP", flag: "🇳🇵", label: "🇳🇵 +977", name: "Nepal" },
  { code: "+31", iso: "NL", flag: "🇳🇱", label: "🇳🇱 +31", name: "Netherlands" },
  { code: "+64", iso: "NZ", flag: "🇳🇿", label: "🇳🇿 +64", name: "New Zealand" },
  { code: "+505", iso: "NI", flag: "🇳🇮", label: "🇳🇮 +505", name: "Nicaragua" },
  { code: "+227", iso: "NE", flag: "🇳🇪", label: "🇳🇪 +227", name: "Niger" },
  { code: "+234", iso: "NG", flag: "🇳🇬", label: "🇳🇬 +234", name: "Nigeria" },
  { code: "+389", iso: "MK", flag: "🇲🇰", label: "🇲🇰 +389", name: "North Macedonia" },
  { code: "+47", iso: "NO", flag: "🇳🇴", label: "🇳🇴 +47", name: "Norway" },
  { code: "+968", iso: "OM", flag: "🇴🇲", label: "🇴🇲 +968", name: "Oman" },
  { code: "+92", iso: "PK", flag: "🇵🇰", label: "🇵🇰 +92", name: "Pakistan" },
  { code: "+680", iso: "PW", flag: "🇵🇼", label: "🇵🇼 +680", name: "Palau" },
  { code: "+970", iso: "PS", flag: "🇵🇸", label: "🇵🇸 +970", name: "Palestine" },
  { code: "+507", iso: "PA", flag: "🇵🇦", label: "🇵🇦 +507", name: "Panama" },
  { code: "+675", iso: "PG", flag: "🇵🇬", label: "🇵🇬 +675", name: "Papua New Guinea" },
  { code: "+595", iso: "PY", flag: "🇵🇾", label: "🇵🇾 +595", name: "Paraguay" },
  { code: "+51", iso: "PE", flag: "🇵🇪", label: "🇵🇪 +51", name: "Peru" },
  { code: "+63", iso: "PH", flag: "🇵🇭", label: "🇵🇭 +63", name: "Philippines" },
  { code: "+48", iso: "PL", flag: "🇵🇱", label: "🇵🇱 +48", name: "Poland" },
  { code: "+351", iso: "PT", flag: "🇵🇹", label: "🇵🇹 +351", name: "Portugal" },
  { code: "+974", iso: "QA", flag: "🇶🇦", label: "🇶🇦 +974", name: "Qatar" },
  { code: "+40", iso: "RO", flag: "🇷🇴", label: "🇷🇴 +40", name: "Romania" },
  { code: "+7", iso: "RU", flag: "🇷🇺", label: "🇷🇺 +7", name: "Russia" },
  { code: "+250", iso: "RW", flag: "🇷🇼", label: "🇷🇼 +250", name: "Rwanda" },
  { code: "+1", iso: "KN", flag: "🇰🇳", label: "🇰🇳 +1", name: "Saint Kitts & Nevis" },
  { code: "+1", iso: "LC", flag: "🇱🇨", label: "🇱🇨 +1", name: "Saint Lucia" },
  { code: "+1", iso: "VC", flag: "🇻🇨", label: "🇻🇨 +1", name: "Saint Vincent" },
  { code: "+685", iso: "WS", flag: "🇼🇸", label: "🇼🇸 +685", name: "Samoa" },
  { code: "+378", iso: "SM", flag: "🇸🇲", label: "🇸🇲 +378", name: "San Marino" },
  { code: "+239", iso: "ST", flag: "🇸🇹", label: "🇸🇹 +239", name: "São Tomé & Príncipe" },
  { code: "+966", iso: "SA", flag: "🇸🇦", label: "🇸🇦 +966", name: "Saudi Arabia" },
  { code: "+221", iso: "SN", flag: "🇸🇳", label: "🇸🇳 +221", name: "Senegal" },
  { code: "+381", iso: "RS", flag: "🇷🇸", label: "🇷🇸 +381", name: "Serbia" },
  { code: "+248", iso: "SC", flag: "🇸🇨", label: "🇸🇨 +248", name: "Seychelles" },
  { code: "+232", iso: "SL", flag: "🇸🇱", label: "🇸🇱 +232", name: "Sierra Leone" },
  { code: "+65", iso: "SG", flag: "🇸🇬", label: "🇸🇬 +65", name: "Singapore" },
  { code: "+421", iso: "SK", flag: "🇸🇰", label: "🇸🇰 +421", name: "Slovakia" },
  { code: "+386", iso: "SI", flag: "🇸🇮", label: "🇸🇮 +386", name: "Slovenia" },
  { code: "+677", iso: "SB", flag: "🇸🇧", label: "🇸🇧 +677", name: "Solomon Islands" },
  { code: "+252", iso: "SO", flag: "🇸🇴", label: "🇸🇴 +252", name: "Somalia" },
  { code: "+27", iso: "ZA", flag: "🇿🇦", label: "🇿🇦 +27", name: "South Africa" },
  { code: "+82", iso: "KR", flag: "🇰🇷", label: "🇰🇷 +82", name: "South Korea" },
  { code: "+211", iso: "SS", flag: "🇸🇸", label: "🇸🇸 +211", name: "South Sudan" },
  { code: "+34", iso: "ES", flag: "🇪🇸", label: "🇪🇸 +34", name: "Spain" },
  { code: "+94", iso: "LK", flag: "🇱🇰", label: "🇱🇰 +94", name: "Sri Lanka" },
  { code: "+249", iso: "SD", flag: "🇸🇩", label: "🇸🇩 +249", name: "Sudan" },
  { code: "+597", iso: "SR", flag: "🇸🇷", label: "🇸🇷 +597", name: "Suriname" },
  { code: "+46", iso: "SE", flag: "🇸🇪", label: "🇸🇪 +46", name: "Sweden" },
  { code: "+41", iso: "CH", flag: "🇨🇭", label: "🇨🇭 +41", name: "Switzerland" },
  { code: "+963", iso: "SY", flag: "🇸🇾", label: "🇸🇾 +963", name: "Syria" },
  { code: "+886", iso: "TW", flag: "🇹🇼", label: "🇹🇼 +886", name: "Taiwan" },
  { code: "+992", iso: "TJ", flag: "🇹🇯", label: "🇹🇯 +992", name: "Tajikistan" },
  { code: "+255", iso: "TZ", flag: "🇹🇿", label: "🇹🇿 +255", name: "Tanzania" },
  { code: "+66", iso: "TH", flag: "🇹🇭", label: "🇹🇭 +66", name: "Thailand" },
  { code: "+670", iso: "TL", flag: "🇹🇱", label: "🇹🇱 +670", name: "Timor-Leste" },
  { code: "+228", iso: "TG", flag: "🇹🇬", label: "🇹🇬 +228", name: "Togo" },
  { code: "+676", iso: "TO", flag: "🇹🇴", label: "🇹🇴 +676", name: "Tonga" },
  { code: "+1", iso: "TT", flag: "🇹🇹", label: "🇹🇹 +1", name: "Trinidad & Tobago" },
  { code: "+216", iso: "TN", flag: "🇹🇳", label: "🇹🇳 +216", name: "Tunisia" },
  { code: "+90", iso: "TR", flag: "🇹🇷", label: "🇹🇷 +90", name: "Turkey" },
  { code: "+993", iso: "TM", flag: "🇹🇲", label: "🇹🇲 +993", name: "Turkmenistan" },
  { code: "+688", iso: "TV", flag: "🇹🇻", label: "🇹🇻 +688", name: "Tuvalu" },
  { code: "+256", iso: "UG", flag: "🇺🇬", label: "🇺🇬 +256", name: "Uganda" },
  { code: "+380", iso: "UA", flag: "🇺🇦", label: "🇺🇦 +380", name: "Ukraine" },
  { code: "+971", iso: "AE", flag: "🇦🇪", label: "🇦🇪 +971", name: "United Arab Emirates" },
  { code: "+44", iso: "GB", flag: "🇬🇧", label: "🇬🇧 +44", name: "United Kingdom" },
  { code: "+1", iso: "US", flag: "🇺🇸", label: "🇺🇸 +1", name: "United States" },
  { code: "+598", iso: "UY", flag: "🇺🇾", label: "🇺🇾 +598", name: "Uruguay" },
  { code: "+998", iso: "UZ", flag: "🇺🇿", label: "🇺🇿 +998", name: "Uzbekistan" },
  { code: "+678", iso: "VU", flag: "🇻🇺", label: "🇻🇺 +678", name: "Vanuatu" },
  { code: "+39", iso: "VA", flag: "🇻🇦", label: "🇻🇦 +39", name: "Vatican City" },
  { code: "+58", iso: "VE", flag: "🇻🇪", label: "🇻🇪 +58", name: "Venezuela" },
  { code: "+84", iso: "VN", flag: "🇻🇳", label: "🇻🇳 +84", name: "Vietnam" },
  { code: "+967", iso: "YE", flag: "🇾🇪", label: "🇾🇪 +967", name: "Yemen" },
  { code: "+260", iso: "ZM", flag: "🇿🇲", label: "🇿🇲 +260", name: "Zambia" },
  { code: "+263", iso: "ZW", flag: "🇿🇼", label: "🇿🇼 +263", name: "Zimbabwe" },
];

export default ALL_COUNTRY_CODES;

/** Resolve a detected country code or ISO against the list, defaulting to +971 */
export function resolveCountryCode(detected: string): string {
  if (!detected) return "+971";
  // Try matching by code
  if (ALL_COUNTRY_CODES.some((c) => c.code === detected)) return detected;
  // Try matching by ISO
  const byIso = ALL_COUNTRY_CODES.find((c) => c.iso === detected.toUpperCase());
  if (byIso) return byIso.code;
  return "+971";
}

/** Priority countries shown at top of dropdown for aviation clients */
export const PRIORITY_COUNTRIES = ["AE", "GB", "US", "SA", "FR", "DE", "CH", "QA", "KW", "BH", "OM"];

/** Returns sorted list with priority countries first */
export function getSortedCountryCodes(): CountryCodeEntry[] {
  const priority = ALL_COUNTRY_CODES.filter(c => PRIORITY_COUNTRIES.includes(c.iso));
  const rest = ALL_COUNTRY_CODES.filter(c => !PRIORITY_COUNTRIES.includes(c.iso));
  return [...priority, ...rest];
}
